version: '3.1'

services:

  db:
    image: postgres
    ports:
      - "5435:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: task-management
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
